#!/usr/bin/env python3
"""
embed-assets.py — Convert asset files (HTML, CSS) into C header string macros.

Usage:
    python3 tools/embed-assets.py <assets_dir> <output.h>

The generated header provides:
    #define PAGE_CAPTIVE  "HTTP/1.1 200 OK\r\n..."   (from index.html)
    #define PAGE_SPLIT    "HTTP/1.1 200 OK\r\n..."   (from split.html)
    #define PAGE_UNSPLIT  "HTTP/1.1 200 OK\r\n..."   (from unsplit.html)

Each HTML can reference "style.css" — the script inlines it automatically.
"""

import os
import sys


def escape_c_string(data: bytes) -> str:
    """Convert bytes to a C string literal with \\r\\n, \\" etc."""
    result = []
    for b in data:
        if b == ord(b'"'):
            result.append('\\"')
        elif b == ord(b'\\'):
            result.append('\\\\')
        elif b == ord(b'\r'):
            result.append('\\r')
        elif b == ord(b'\n'):
            result.append('\\n')
        elif 32 <= b < 127:
            result.append(chr(b))
        else:
            result.append(f'\\x{b:02x}')
    return ''.join(result)


def read_file(path: str) -> bytes:
    with open(path, 'rb') as f:
        return f.read()


def build_page(html_raw: str, css_raw: str | None, assets_dir: str, qr_max_dim: int, server_decode: bool) -> str:
    """Inline CSS and JS into HTML, then wrap with HTTP response headers."""
    if css_raw is not None:
        html_raw = html_raw.replace('<link rel="stylesheet" href="style.css">',
                                    f'<style>\n{css_raw}\n</style>')
        html_raw = html_raw.replace("<link rel='stylesheet' href='style.css'>",
                                    f'<style>\n{css_raw}\n</style>')

    # On boards without on-device decoding (classic ESP32), the page decodes
    # locally with jsQR: inline it right before unsplit.js so it is defined
    # when unsplit.js runs. On ESP32-S3 the device decodes, so jsQR stays out.
    import re
    if not server_decode:
        html_raw = re.sub(
            r'(<script\s+src="scripts/unsplit\.js[^"]*"\s*></script\s*>)',
            '<script src="scripts/jsQR.js"></script>\n\\1',
            html_raw,
        )

    # Inline JavaScript files: <script src="scripts/foo.js"></script>
    from urllib.parse import urlparse
    def inline_js(match):
        src = match.group(1)
        # Strip query string (e.g. ?v=2) — used for cache busting on GH Pages
        path_only = urlparse(src).path
        js_path = os.path.join(assets_dir, path_only)
        if os.path.isfile(js_path):
            js_raw = read_file(js_path).decode('utf-8')
            return f'<script>\n{js_raw}\n</script>'
        return match.group(0)  # file not found — leave as-is

    html_raw = re.sub(
        r'<script\s+src="(scripts/[^"\s]+)"\s*></script\s*>',
        inline_js,
        html_raw,
    )

    # Bake the per-board settings into the page:
    # - __QR_MAX_DIM__: max grayscale dimension for on-device decode. In the
    #   WASM demo (raw files, no substitution) the placeholder remains, so
    #   unsplit.js falls back to its default of 224.
    # - __QR_DECODE_SERVER__: 1 when the device decodes (ESP32-S3), 0 when the
    #   page must decode locally with jsQR (classic ESP32).
    html_raw = html_raw.replace('__QR_MAX_DIM__', str(qr_max_dim))
    html_raw = html_raw.replace('__QR_DECODE_SERVER__', '1' if server_decode else '0')

    return (
        "HTTP/1.1 200 OK\r\n"
        "Content-Type: text/html\r\n"
        "Connection: close\r\n"
        "\r\n"
        f"{html_raw}\r\n"
    )


def main():
    import argparse

    parser = argparse.ArgumentParser(description='Embed assets into a C header.')
    parser.add_argument('--qr-max-dim', type=int, default=224,
                        help='Maximum QR decode image dimension (px) baked into the page.')
    parser.add_argument('--qr-decode-server', type=int, default=1, choices=(0, 1),
                        help='1 if the device decodes QR codes (quirc or ZXing), 0 if the page decodes locally (jsQR).')
    parser.add_argument('assets_dir', help='Directory containing the HTML/CSS/JS assets.')
    parser.add_argument('output', help='Output C header path.')
    args = parser.parse_args()

    assets_dir = args.assets_dir
    output_path = args.output
    qr_max_dim = args.qr_max_dim
    server_decode = bool(args.qr_decode_server)

    # Read CSS once — shared by all pages
    css_path = os.path.join(assets_dir, 'style.css')
    css_raw = None
    if os.path.isfile(css_path):
        css_raw = read_file(css_path).decode('utf-8')

    # Define pages: (html_filename, macro_name)
    pages = [
        ('index.html',  'PAGE_CAPTIVE'),
        ('split.html',  'PAGE_SPLIT'),
        ('unsplit.html','PAGE_UNSPLIT'),
    ]

    # Write output header
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    with open(output_path, 'w') as f:
        f.write("/* Auto-generated by embed-assets.py — do not edit */\n")
        f.write("#ifndef ASSETS_PAGE_CAPTIVE_H\n")
        f.write("#define ASSETS_PAGE_CAPTIVE_H\n\n")

        for html_name, macro_name in pages:
            html_path = os.path.join(assets_dir, html_name)
            if not os.path.isfile(html_path):
                print(f"Warning: {html_path} not found, skipping {macro_name}", file=sys.stderr)
                continue

            html_raw = read_file(html_path).decode('utf-8')
            http_response = build_page(html_raw, css_raw, assets_dir, qr_max_dim, server_decode)
            escaped = escape_c_string(http_response.encode('utf-8'))
            f.write(f'#define {macro_name} "{escaped}"\n\n')

            size = len(http_response)
            print(f"  {macro_name:20s} {size:5d} bytes  ({html_name})")

        f.write("#endif /* ASSETS_PAGE_CAPTIVE_H */\n")

    print(f"✅ Generated {output_path}")


if __name__ == '__main__':
    main()
